=== v4m3rrr/HackArena2.5-StereoTanks/GameClient/Content/Localization/Language.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Language"
           targetNamespace="http://tempuri.org/Language.xsd"
           elementFormDefault="qualified"
           xmlns="http://tempuri.org/Language.xsd"
           xmlns:mstns="http://tempuri.org/Language.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="Buttons">
		<xs:sequence>
			<xs:element name="Ok" type="xs:string"/>
			<xs:element name="JoinGame" type="xs:string"/>
			<xs:element name="SinglePlayer" type="xs:string"/>
			<xs:element name="Cooperation" type="xs:string"/>
			<xs:element name="Play" type="xs:string"/>
			<xs:element name="Settings" type="xs:string"/>
			<xs:element name="WatchReplay" type="xs:string"/>
			<xs:element name="Exit" type="xs:string"/>
			<xs:element name="Back" type="xs:string"/>
			<xs:element name="Close" type="xs:string"/>
			<xs:element name="Leave" type="xs:string"/>
			<xs:element name="LeaveMatch" type="xs:string"/>
			<xs:element name="Stay" type="xs:string"/>
			<xs:element name="Continue" type="xs:string"/>
			<xs:element name="Menu" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Labels">
		<xs:sequence>
			<xs:element name="Language" type="xs:string"/>
			<xs:element name="Resolution" type="xs:string"/>
			<xs:element name="DisplayMode" type="xs:string"/>
			<xs:element name="DisplayModeWindowed" type="xs:string"/>
			<xs:element name="DisplayModeFullScreen" type="xs:string"/>
			<xs:element name="DisplayModeBorderless" type="xs:string"/>
			<xs:element name="SingleplayerRoom" type="xs:string"/>
			<xs:element name="CoopRoom" type="xs:string"/>
			<xs:element name="JoinRoom" type="xs:string"/>
			<xs:element name="Nickname" type="xs:string"/>
			<xs:element name="TeamName" type="xs:string"/>
			<xs:element name="TankType" type="xs:string"/>
			<xs:element name="Difficulty" type="xs:string"/>
			<xs:element name="RoomCode" type="xs:string"/>
			<xs:element name="ServerAddress" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="MessageBoxLabels">
		<xs:sequence>
			<xs:element name="ErrorOccurred" type="xs:string"/>
			<xs:element name="ConnectionFailed" type="xs:string"/>
			<xs:element name="ConnectionRejected" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ConnectionRejectedReason">
		<xs:sequence>
			<xs:element name="InvalidJoinCode" type="xs:string"/>
			<xs:element name="MissingNickname" type="xs:string"/>
			<xs:element name="MissingTeamName" type="xs:string"/>
			<xs:element name="InvalidTankType" type="xs:string"/>
			<xs:element name="NicknameExists" type="xs:string"/>
			<xs:element name="InvalidUrlPath" type="xs:string"/>
			<xs:element name="GameFull" type="xs:string"/>
			<xs:element name="GameInProgress" type="xs:string"/>
			<xs:element name="TeamFull" type="xs:string"/>
			<xs:element name="TankTypeTaken" type="xs:string"/>
			<xs:element name="TooManyFailedAttempts" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ConfirmQuestion">
		<xs:sequence>
			<xs:element name="LeaveMatch" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Other">
		<xs:sequence>
			<xs:element name="Light" type="xs:string"/>
			<xs:element name="Heavy" type="xs:string"/>
			<xs:element name="Easy" type="xs:string"/>
			<xs:element name="Medium" type="xs:string"/>
			<xs:element name="Hard" type="xs:string"/>
			<xs:element name="Loading" type="xs:string"/>
			<xs:element name="Waiting" type="xs:string"/>
			<xs:element name="Connecting" type="xs:string"/>
			<xs:element name="NoDetails" type="xs:string"/>
			<xs:element name="ServerNotResponding" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="Content">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Buttons" type="mstns:Buttons"/>
				<xs:element name="Labels" type="mstns:Labels"/>
				<xs:element name="MessageBoxLabels" type="mstns:MessageBoxLabels"/>
				<xs:element name="ConnectionRejectedReason" type="mstns:ConnectionRejectedReason"/>
				<xs:element name="ConfirmQuestion" type="mstns:ConfirmQuestion"/>
				<xs:element name="Other" type="mstns:Other"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== v4m3rrr/HackArena2.5-StereoTanks/GameClient/Content/Localization/English.xml
<?xml version="1.0" encoding="utf-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://tempuri.org/Language.xsd"
         xsi:schemaLocation="http://tempuri.org/Language.xsd Language.xsd">

	<Buttons>
		<Ok>Ok</Ok>
		<JoinGame>Join</JoinGame>
		<SinglePlayer>Singleplayer</SinglePlayer>
    <Play>Play</Play>
		<Settings>Settings</Settings>
		<WatchReplay>Watch replay</WatchReplay>
		<Exit>Exit</Exit>
		<Back>Back</Back>
		<Close>Close</Close>
		<Leave>Leave</Leave>
		<LeaveMatch>Leave match</LeaveMatch>
		<Stay>Stay</Stay>
		<Continue>Continue</Continue>
		<Menu>Menu</Menu>
	</Buttons>

	<Labels>
		<Language>Language</Language>
		<Resolution>Resolution</Resolution>
		<DisplayMode>Display mode</DisplayMode>
		<DisplayModeWindowed>Windowed</DisplayModeWindowed>
		<DisplayModeFullScreen>Fullscreen</DisplayModeFullScreen>
		<DisplayModeBorderless>Borderless</DisplayModeBorderless>
		<JoinRoom>Join room</JoinRoom>
		<Nickname>Nickname</Nickname>
		<TeamName>Team name</TeamName>
		<TankType>Tank type</TankType>
		<Difficulty>Difficulty</Difficulty>
		<RoomCode>Room code</RoomCode>
		<ServerAddress>Server address</ServerAddress>
	</Labels>

	<MessageBoxLabels>
		<ErrorOccurred>Oh no! An error occurred!</ErrorOccurred>
		<ConnectionFailed>Connection failed</ConnectionFailed>
		<ConnectionRejected>Connection rejected</ConnectionRejected>
	</MessageBoxLabels>
	
	<ConnectionRejectedReason>
		<InvalidJoinCode>Invalid join code!</InvalidJoinCode>
		<MissingNickname>Nickname is required!</MissingNickname>
		<MissingTeamName>Team name is required!</MissingTeamName>
		<InvalidTankType>Invalid tank type!</InvalidTankType>
		<NicknameExists>Nickname already exists!</NicknameExists>
		<InvalidUrlPath>Invalid URL path!</InvalidUrlPath>
		<GameFull>Game is full!</GameFull>
		<GameInProgress>Game is in progress!</GameInProgress>
		<TeamFull>Team is full!</TeamFull>
		<TankTypeTaken>Tank type is already taken!</TankTypeTaken>
		<TooManyFailedAttempts>Too many failed attempts! Try again later.</TooManyFailedAttempts>
	</ConnectionRejectedReason>

	<ConfirmQuestion>
		<LeaveMatch>Are you sure you want to leave the match?</LeaveMatch>
	</ConfirmQuestion>

	<Other>
		<Light>Light</Light>
		<Heavy>Heavy</Heavy>
		<Easy>Easy</Easy>
		<Medium>Medium</Medium>
		<Hard>Hard</Hard>
		<Loading>Loading</Loading>
		<Waiting>Waiting</Waiting>
		<Connecting>Connecting</Connecting>
		<NoDetails>No details.</NoDetails>
		<ServerNotResponding>Server is not responding.</ServerNotResponding>
	</Other>

</Content>

=== v4m3rrr/HackArena2.5-StereoTanks/GameClient/Content/Localization/French.xml
<?xml version="1.0" encoding="utf-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://tempuri.org/Language.xsd"
         xsi:schemaLocation="http://tempuri.org/Language.xsd Language.xsd">

	<Buttons>
		<Ok>Ok</Ok>
		<JoinGame>Rejoindre</JoinGame>
		<SinglePlayer>Solo</SinglePlayer>
		<Settings>Paramètres</Settings>
		<WatchReplay>Rediffusions</WatchReplay>
		<Exit>Quitter</Exit>
		<Back>Retour</Back>
		<Close>Fermer</Close>
		<Leave>Quitter</Leave>
		<LeaveMatch>Quitter le match</LeaveMatch>
		<Stay>Rester</Stay>
		<Continue>Continuer</Continue>
		<Menu>Menu</Menu>
	</Buttons>

	<Labels>
		<Language>Langue</Language>
		<Resolution>Résolution d'écran</Resolution>
		<DisplayMode>Mode d'affichage</DisplayMode>
		<DisplayModeWindowed>Fenêtré</DisplayModeWindowed>
		<DisplayModeFullScreen>Plein écran</DisplayModeFullScreen>
		<DisplayModeBorderless>Sans bordure</DisplayModeBorderless>
		<JoinRoom>Rejoindre une salle</JoinRoom>
		<Nickname>Surnom</Nickname>
		<TeamName>Nom de l'équipe</TeamName>
		<TankType>Type de char</TankType>
		<RoomCode>Code de la salle</RoomCode>
		<ServerAddress>Adresse du serveur</ServerAddress>
	</Labels>
	
	<MessageBoxLabels>
		<ErrorOccurred>Oh non, une erreur est survenue!</ErrorOccurred>
		<ConnectionFailed>Échec de la connexion</ConnectionFailed>
		<ConnectionRejected>Connexion rejetée</ConnectionRejected>
	</MessageBoxLabels>
	
	<ConnectionRejectedReason>
		<InvalidJoinCode>Le code de connexion est invalide!</InvalidJoinCode>
		<MissingNickname>Le surnom est requis!</MissingNickname>
		<MissingTeamName>Le nom de l'équipe est requis!</MissingTeamName>
		<InvalidTankType>Type de char invalide!</InvalidTankType>
		<NicknameExists>Ce surnom est déjà utilisé!</NicknameExists>
		<InvalidUrlPath>Chemin d'URL invalide!</InvalidUrlPath>
		<GameFull>La salle est pleine!</GameFull>
		<GameInProgress>La partie est en cours!</GameInProgress>
		<TeamFull>L'équipe est pleine!</TeamFull>
		<TankTypeTaken>Type de char déjà pris!</TankTypeTaken>
		<TooManyFailedAttempts>Trop de tentatives échouées! Réessayez plus tard.</TooManyFailedAttempts>
	</ConnectionRejectedReason>
	
	<ConfirmQuestion>
		<LeaveMatch>Êtes-vous sûr de vouloir quitter le match?</LeaveMatch>
	</ConfirmQuestion>

	<Other>
		<Light>Léger</Light>
		<Heavy>Lourd</Heavy>
		<Loading>Chargement</Loading>
		<Waiting>En attente</Waiting>
		<Connecting>Connexion en cours</Connecting>
		<NoDetails>Aucun détail.</NoDetails>
		<ServerNotResponding>Le serveur ne répond pas.</ServerNotResponding>
	</Other>

</Content>

=== v4m3rrr/HackArena2.5-StereoTanks/GameClient/Content/Localization/Polish.xml
<?xml version="1.0" encoding="utf-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://tempuri.org/Language.xsd"
         xsi:schemaLocation="http://tempuri.org/Language.xsd Language.xsd">

	<Buttons>
		<Ok>Ok</Ok>
		<JoinGame>Dołącz</JoinGame>
		<SinglePlayer>Gra dla jednego gracza</SinglePlayer>
		<Settings>Ustawienia</Settings>
		<WatchReplay>Powtórki</WatchReplay>
		<Exit>Wyjście</Exit>
		<Back>Wróć</Back>
		<Close>Zamknij</Close>
		<Leave>Opuść</Leave>
		<LeaveMatch>Opuść mecz</LeaveMatch>
		<Stay>Zostań</Stay>
		<Continue>Kontynuuj</Continue>
		<Menu>Menu</Menu>
	</Buttons>

	<Labels>
		<Language>Język</Language>
		<Resolution>Rozdzielczość</Resolution>
		<DisplayMode>Tryb wyświetlania</DisplayMode>
		<DisplayModeWindowed>Okienkowy</DisplayModeWindowed>
		<DisplayModeFullScreen>Pełny ekran</DisplayModeFullScreen>
		<DisplayModeBorderless>Bezramkowy</DisplayModeBorderless>
		<JoinRoom>Dołącz do pokoju</JoinRoom>
		<Nickname>Nazwa gracza</Nickname>
		<TeamName>Nazwa drużyny</TeamName>
		<TankType>Typ czołgu</TankType>
		<RoomCode>Kod pokoju</RoomCode>
		<ServerAddress>Adres serwera</ServerAddress>
	</Labels>
	
	<MessageBoxLabels>
		<ErrorOccurred>Ups, coś poszło nie tak!</ErrorOccurred>
		<ConnectionFailed>Połączenie nieudane</ConnectionFailed>
		<ConnectionRejected>Połączenie odrzucone</ConnectionRejected>
	</MessageBoxLabels>
	
	<ConnectionRejectedReason>
		<InvalidJoinCode>Nieprawidłowy kod dołączenia!</InvalidJoinCode>
		<MissingNickname>Nazwa gracza jest wymagana!</MissingNickname>
		<MissingTeamName>Nazwa drużyny jest wymagana!</MissingTeamName>
		<InvalidTankType>Nieprawidłowy typ czołgu!</InvalidTankType>
		<NicknameExists>Gracz o takiej nazwie już istnieje!</NicknameExists>
		<InvalidUrlPath>Nieprawidłowa ścieżka URL!</InvalidUrlPath>
		<GameFull>Pokój jest pełny!</GameFull>
		<GameInProgress>Gra już trwa!</GameInProgress>
		<TeamFull>Drużyna jest pełna!</TeamFull>
		<TankTypeTaken>Typ czołgu jest już zajęty!</TankTypeTaken>
		<TooManyFailedAttempts>Za dużo nieudanych prób! Spróbuj ponownie później.</TooManyFailedAttempts>
	</ConnectionRejectedReason>

	<ConfirmQuestion>
		<LeaveMatch>Czy na pewno chcesz opuścić mecz?</LeaveMatch>
	</ConfirmQuestion>

	<Other>
		<Light>Lekki</Light>
		<Heavy>Ciężki</Heavy>
		<Loading>Wczytywanie</Loading>
		<Waiting>Oczekiwanie</Waiting>
		<Connecting>Łączenie</Connecting>
		<NoDetails>Brak szczegółów.</NoDetails>
		<ServerNotResponding>Serwer nie odpowiada.</ServerNotResponding>
	</Other>
</Content>

=== v4m3rrr/HackArena2.5-StereoTanks/GameClient/Content/Localization/Russian.xml
<?xml version="1.0" encoding="utf-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://tempuri.org/Language.xsd"
         xsi:schemaLocation="http://tempuri.org/Language.xsd Language.xsd">

	<Buttons>
		<Ok>ОК</Ok>
		<JoinGame>Присоединиться</JoinGame>
		<SinglePlayer>Oдиночная игра</SinglePlayer>
		<Settings>Настройки</Settings>
		<WatchReplay>Смотреть повторы</WatchReplay>
		<Exit>Выход</Exit>
		<Back>Назад</Back>
		<Close>Закрыть</Close>
		<Leave>Покинуть</Leave>
		<LeaveMatch>Покинуть матч</LeaveMatch>
		<Stay>Остаться</Stay>
		<Continue>Продолжить</Continue>
		<Menu>Меню</Menu>
	</Buttons>

	<Labels>
		<Language>Язык</Language>
		<Resolution>Разрешение</Resolution>
		<DisplayMode>Режим отображения</DisplayMode>
		<DisplayModeWindowed>Оконный</DisplayModeWindowed>
		<DisplayModeFullScreen>Полноэкранный</DisplayModeFullScreen>
		<DisplayModeBorderless>Безрамочный режим</DisplayModeBorderless>
		<JoinRoom>Присоединиться к комнате</JoinRoom>
		<Nickname>Имя игрока</Nickname>
		<TeamName>Имя команды</TeamName>
		<TankType>Тип танка</TankType>
		<RoomCode>Код комнаты</RoomCode>
		<ServerAddress>Адрес сервера</ServerAddress>
	</Labels>

	<MessageBoxLabels>
		<ErrorOccurred>Упс, что-то пошло не так!</ErrorOccurred>
		<ConnectionFailed>Не удалось подключиться</ConnectionFailed>
		<ConnectionRejected>Подключение отклонено</ConnectionRejected>
	</MessageBoxLabels>

	<ConnectionRejectedReason>
		<InvalidJoinCode>Неверный код подключения!</InvalidJoinCode>
		<MissingNickname>Требуется имя игрока!</MissingNickname>
		<MissingTeamName>Требуется имя команды!</MissingTeamName>
		<InvalidTankType>Неверный тип танка!</InvalidTankType>
		<NicknameExists>Игрок с таким именем уже существует!</NicknameExists>
		<InvalidUrlPath>Неверный путь URL!</InvalidUrlPath>
		<GameFull>Лобби заполнено!</GameFull>
		<GameInProgress>Игра уже идет!</GameInProgress>
		<TeamFull>Команда заполнена!</TeamFull>
		<TankTypeTaken>Тип танка уже занят!</TankTypeTaken>
		<TooManyFailedAttempts>Слишком много неудачных попыток! Попробуйте снова позже.</TooManyFailedAttempts>
	</ConnectionRejectedReason>

	<ConfirmQuestion>
		<LeaveMatch>Вы уверены, что хотите покинуть матч?</LeaveMatch>
	</ConfirmQuestion>

	<Other>
		<Light>Легкий</Light>
		<Heavy>Тяжёлый</Heavy>
		<Loading>Загрузка</Loading>
		<Waiting>Ожидание</Waiting>
		<Connecting>Подключение</Connecting>
		<NoDetails>Нет деталей.</NoDetails>
		<ServerNotResponding>Сервер не отвечает.</ServerNotResponding>
	</Other>

</Content>
